spring:
  application:
    name: ScholarArcanumAgent
server:
  port: 8129
  servlet:
    context-path: /saa/api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.nahcooo.scholararcanumagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
